### ISSUE TITLE
 Windows 服务能否修改同步频率

### ISSUE THREAD

**Issue by norcx** [viazure/EudicSyncToMaiMemo#3]
当设置为 Windows 服务时，程序将自动每 7 天同步一次。

请问这个频率能否修改

**Comment by viazure** [comment]
> 当设置为 Windows 服务时，程序将自动每 7 天同步一次。
> 
> 请问这个频率能否修改

暂时还不行，目前是在代码里固定的7天。如果有这方面的需求，后续会考虑增加同步频率的自定义配置。

**Comment by viazure** [comment]
更新了一个版本 [Release v1.1.1](https://github.com/viazure/EudicSyncToMaiMemo/releases/tag/v1.1.1)，暂时新增了一个配置：同步间隔天数（SyncInterval）。后续有必要再调整为更灵活的实现方案了。

**Comment by norcx** [comment]
伟大！！！
